In [1]:
# Ne kete file jan rregjistruar kliente nga vende te ndryshme dhe jane rregj blerjet e tyre, sasia, lloji dhe cmimi per produkt
# do te gjejme cili shtet ka me shume blerje
# do te shoshim tek ky shtet totalin e blerjeve * cmimin, sa eshte harxhuar

In [2]:
import pandas as pd
import numpy as np

In [2]:
# hapja e nje file 'big' ne excel dhe konvertimi i tij ne csv
data = pd.read_excel("Online retail.xlsx")
data.head(5)


InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

          InvoiceDate  UnitPrice  CustomerID         Country  
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype         
---  ------       --------------  -----         
 0   InvoiceNo    10000 non-null  object        
 1   StockCode    10000 non-null  object        
 2   Description  9958 non-null   object        
 3   Quantity     10000 non-null  int64         
 4   InvoiceDate  10000 non-null  datetime64[ns]
 5   UnitPrice    10000 non-null  float64       
 6   CustomerID   7709 non-null   float64       
 7   Country      10000 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 625.1+ KB


In [3]:
data.to_csv("NwData.csv", index = False)

NameError: name 'data' is not defined

In [4]:
data = pd.read_csv("NwData.csv")
data.head()

InvoiceNo StockCode  Quantity  UnitPrice         Country  id_data
0    536365    85123A         6       2.55  United Kingdom        1
1    536365     71053         6       3.39  United Kingdom        2
2    536365    84406B         8       2.75  United Kingdom        3
3    536365    84029G         6       3.39  United Kingdom        4
4    536365    84029E         6       3.39  United Kingdom        5

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   InvoiceNo  10000 non-null  object 
 1   StockCode  10000 non-null  object 
 2   Quantity   10000 non-null  int64  
 3   UnitPrice  10000 non-null  float64
 4   Country    10000 non-null  object 
 5   id_data    10000 non-null  int64  
dtypes: float64(1), int64(2), object(3)
memory usage: 468.9+ KB


In [7]:
# per kerkesat e mia po heq disa kolona
data.drop(['Description','CustomerID', 'InvoiceDate'],axis='columns', inplace=True)
data.info()

KeyError: "['Description', 'CustomerID', 'InvoiceDate'] not found in axis"

In [8]:
# gjej sa nr unik faturash kam, keshtu gjej dhe sa 
# fatura me jane gjeneruar ne kete hapeise kohe
data['InvoiceNo'].nunique()

512

In [9]:
data['StockCode'].nunique() # mund te them qe kam 2015 produkte

2015

In [10]:
data['Quantity'].isna().sum().sum() # nuk kam asnje velere boshe NA tek kolona quantitu

0

In [11]:
# shohim nga leximet me 
# siper qe ne te dhenat e mia nuk kam nje index unik ytekolonave ekzistuese
# mund te shtoj nje kolone id
data['id_data']= range(1, 10001)
data.head()

InvoiceNo StockCode  Quantity  UnitPrice         Country  id_data
0    536365    85123A         6       2.55  United Kingdom        1
1    536365     71053         6       3.39  United Kingdom        2
2    536365    84406B         8       2.75  United Kingdom        3
3    536365    84029G         6       3.39  United Kingdom        4
4    536365    84029E         6       3.39  United Kingdom        5

In [12]:
data.to_csv("NwData.csv", index=False)

In [8]:
data = pd.read_csv("NwData.csv", index_col="id_data")
data.head()

InvoiceNo StockCode  Quantity  UnitPrice         Country
id_data                                                         
1          536365    85123A         6       2.55  United Kingdom
2          536365     71053         6       3.39  United Kingdom
3          536365    84406B         8       2.75  United Kingdom
4          536365    84029G         6       3.39  United Kingdom
5          536365    84029E         6       3.39  United Kingdom

In [9]:
data.drop_duplicates(inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9804 entries, 1 to 10000
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   InvoiceNo  9804 non-null   object 
 1   StockCode  9804 non-null   object 
 2   Quantity   9804 non-null   int64  
 3   UnitPrice  9804 non-null   float64
 4   Country    9804 non-null   object 
dtypes: float64(1), int64(1), object(3)
memory usage: 459.6+ KB


In [10]:
data.describe()

Quantity    UnitPrice
count  9804.000000  9804.000000
mean      7.945328     3.866496
std     105.355599    14.448900
min   -9360.000000     0.000000
25%       1.000000     1.250000
50%       3.000000     2.510000
75%       8.000000     4.210000
max    2880.000000   887.520000

https://statisticsbyjim.com/basics/outliers/   study outliers

In [11]:
# funksion per fshirjen e outliers
def drop_outliers (data):
    q1 = data.quantile(0.25)
    q3 = data.quantile(0.75)
    IQR =q3-q1
    not_outliers = data[~((data < (q1-1.5*IQR)) | (data > (q3+1.5*IQR)))]
    return not_outliers

In [12]:
data['Quantity'] = drop_outliers(data['Quantity'])
data['Quantity'].describe()

count    8799.000000
mean        4.011933
std         3.948258
min        -8.000000
25%         1.000000
50%         2.000000
75%         6.000000
max        18.000000
Name: Quantity, dtype: float64

In [13]:
data['UnitPrice'] = drop_outliers(data['UnitPrice'])
data['UnitPrice'].describe()

count    9176.000000
mean        2.780814
std         2.030931
min         0.000000
25%         1.250000
50%         2.100000
75%         3.750000
max         8.500000
Name: UnitPrice, dtype: float64

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9804 entries, 1 to 10000
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   InvoiceNo  9804 non-null   object 
 1   StockCode  9804 non-null   object 
 2   Quantity   8799 non-null   float64
 3   UnitPrice  9176 non-null   float64
 4   Country    9804 non-null   object 
dtypes: float64(2), object(3)
memory usage: 459.6+ KB


In [15]:
data.dropna(inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8183 entries, 1 to 10000
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   InvoiceNo  8183 non-null   object 
 1   StockCode  8183 non-null   object 
 2   Quantity   8183 non-null   float64
 3   UnitPrice  8183 non-null   float64
 4   Country    8183 non-null   object 
dtypes: float64(2), object(3)
memory usage: 383.6+ KB


In [16]:
data.describe()

Quantity    UnitPrice
count  8183.000000  8183.000000
mean      4.175852     2.937699
std       4.008363     2.040107
min      -7.000000     0.000000
25%       1.000000     1.280000
50%       2.000000     2.510000
75%       6.000000     3.750000
max      18.000000     8.500000

In [17]:
# vlerat negative te quantity po i kthej ne pozitive qe ti jap kuptim
array_quant = np.array(data['Quantity'])



In [18]:
# m1
array_positv = np.absolute(array_quant)

In [21]:
# m2
array_positv = np.where(array_quant<0, array_quant*(-1), array_quant)
array_positv.min()


1.0

In [22]:
data['Quantity']= array_positv.tolist()
data.describe()

Quantity    UnitPrice
count  8183.000000  8183.000000
mean      4.213736     2.937699
std       3.968514     2.040107
min       1.000000     0.000000
25%       1.000000     1.280000
50%       2.000000     2.510000
75%       6.000000     3.750000
max      18.000000     8.500000

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8183 entries, 1 to 10000
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   InvoiceNo  8183 non-null   object 
 1   StockCode  8183 non-null   object 
 2   Quantity   8183 non-null   float64
 3   UnitPrice  8183 non-null   float64
 4   Country    8183 non-null   object 
dtypes: float64(2), object(3)
memory usage: 383.6+ KB


Kemi mbaruar me rregullimin dh e strukturimin e filet te te dhenave
Do te vazhdojme me kerkesta me poshte:
# do te gjejme cili shtet ka me shume blerje
# do te shoshim tek ky shtet totalin e blerjeve * cmimin, sa eshte harxhuar

In [24]:
country_name, country_count = np.unique(data['Country'], return_counts=True)

In [25]:
country_name

array(['Australia', 'Belgium', 'EIRE', 'France', 'Germany', 'Italy',
       'Japan', 'Lithuania', 'Norway', 'Poland', 'Portugal',
       'Switzerland', 'United Kingdom'], dtype=object)

In [26]:
country_count

array([  12,    4,   70,   65,  140,   22,   14,   23,   26,    4,    6,
          2, 7795], dtype=int64)

nga gjithe veprimet me siper arrij ne perfundimin se shteti me me shume shitje eshte UK

In [27]:
data_uk = data[data['Country']=='United Kingdom']
data_uk.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7795 entries, 1 to 10000
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   InvoiceNo  7795 non-null   object 
 1   StockCode  7795 non-null   object 
 2   Quantity   7795 non-null   float64
 3   UnitPrice  7795 non-null   float64
 4   Country    7795 non-null   object 
dtypes: float64(2), object(3)
memory usage: 365.4+ KB


In [29]:
data_uk.to_csv('ukfile.csv')

In [30]:
data_uk = pd.read_csv('ukfile.csv')

In [31]:
data.head()

InvoiceNo StockCode  Quantity  UnitPrice         Country
id_data                                                         
1          536365    85123A       6.0       2.55  United Kingdom
2          536365     71053       6.0       3.39  United Kingdom
3          536365    84406B       8.0       2.75  United Kingdom
4          536365    84029G       6.0       3.39  United Kingdom
5          536365    84029E       6.0       3.39  United Kingdom

In [34]:
data_uk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7795 entries, 0 to 7794
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   id_data    7795 non-null   int64  
 1   InvoiceNo  7795 non-null   object 
 2   StockCode  7795 non-null   object 
 3   Quantity   7795 non-null   float64
 4   UnitPrice  7795 non-null   float64
 5   Country    7795 non-null   object 
 6   TotAmount  6272 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 426.4+ KB


In [38]:
data_uk['TotAmount'] = data_uk['UnitPrice']* data_uk['Quantity']

In [39]:
data_uk.head()

id_data InvoiceNo StockCode  Quantity  UnitPrice         Country  TotAmount
0        1    536365    85123A       6.0       2.55  United Kingdom      15.30
1        2    536365     71053       6.0       3.39  United Kingdom      20.34
2        3    536365    84406B       8.0       2.75  United Kingdom      22.00
3        4    536365    84029G       6.0       3.39  United Kingdom      20.34
4        5    536365    84029E       6.0       3.39  United Kingdom      20.34

In [41]:
tot_amount = data_uk['TotAmount']
unit_price = data_uk['UnitPrice']
quantity = data_uk['Quantity']

une ndertova 3 variabla per te pare korrelacionin midis tyre
lidhja qe do te studioj eshte sasia  e parave te shpenzuara varet me shume nga cmimi i produktit apo nga sasia e blere

In [42]:
np.cov(tot_amount, quantity)

array([[118.00786786,  25.29085447],
       [ 25.29085447,  14.71198608]])

In [43]:
np.corrcoef(tot_amount, quantity)

array([[1.        , 0.60697719],
       [0.60697719, 1.        ]])

In [46]:
np.cov(tot_amount, unit_price)

array([[118.00786786,   8.32749927],
       [  8.32749927,   4.13757319]])

In [44]:
np.corrcoef(tot_amount, unit_price)

array([[1.        , 0.37686541],
       [0.37686541, 1.        ]])

Nga koeficentet e korrelacionit shoh qe lidhja e shpenzimeve me sasine e produktit eshte me e forte se sa me cmimin. Mund te krijoj nje ide qe konsumatori blen me shumeice por me cmim te ulet