In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\agexh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pip\_internal\utils\logging.py", line 177, in emit
    self.console.print(renderable, overflow="ignore", crop=False, style=style)
  File "C:\Users\agexh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pip\_vendor\rich\console.py", line 1699, in print
    extend(render(renderable, render_options))
  File "C:\Users\agexh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pip\_vendor\rich\console.py", line 1331, in render
    for render_output in iter_render:
  File "C:\Users\agexh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pip\_internal\utils\logging.py", line 134, in _

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# vektro 0-D
arr=np.array(45)
arr

array(45)

In [6]:
# ndarray 1-D
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
# ndarray 2-D
arr = np.array([[1,2,3,4,5], [5,6,7,8,9]])
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [8]:
# dimensioni i ndarray
arr1=np.array(45)
arr2 = np.array([1,2,3,4,5])
arr3 = np.array([[1,2,3,4,5], [5,6,7,8,9]])
arr4 = np.array([[[1,2,3,4,5], [5,6,7,8,9]],[[1,2,3,4,5], [5,6,7,8,9]]])

In [9]:
arr4

array([[[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]],

       [[1, 2, 3, 4, 5],
        [5, 6, 7, 8, 9]]])

In [10]:
print("1: ",arr1.ndim)
print("2: ",arr2.ndim)
print("3: ",arr3.ndim)
print("4: ",arr4.ndim)

1:  0
2:  1
3:  2
4:  3


In [11]:
# Slicing @D vektor/array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]) # [[],2,3]
print(arr)
print(arr[1,1:4])

print(arr[0:2,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]


In [12]:
arr_copy = arr.copy()
arr_copy

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
arr1 = np.array([1,2,3,4,5,6,7])
for x in arr1:
    print(x)

1
2
3
4
5
6
7


In [14]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
for x in arr2:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10


In [15]:
arr4 = np.array([[[1,2,3,4,5], [5,6,7,8,9]],[[1,2,3,4,5], [5,6,7,8,9]]])
for x in arr4:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
5
6
7
8
9
1
2
3
4
5
5
6
7
8
9


In [16]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

arr_0 = np.concatenate((arr1, arr2), axis=0)
arr_1 = np.concatenate((arr1, arr2), axis=1)

print(arr1, arr2)
print(arr_0, arr_1)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]] [[1 2 5 6]
 [3 4 7 8]]


In [17]:
# metoda split per te ndare array
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,15])
new_arr = np.array_split(arr, 4)
new_arr

[array([1, 2, 3, 4]),
 array([5, 6, 7]),
 array([ 8,  9, 10]),
 array([11, 12, 15])]

In [18]:
new_arr[1]

array([5, 6, 7])

In [19]:
# kerkojme pozicionet e nje elementi te caktuar ne vektor
arr = np.array([1,2,2,2,4,6,2,7,8,9])
x2 = np.where(arr == 2)
x2

(array([1, 2, 3, 6], dtype=int64),)

In [20]:
# do te gjejme indexet e elem cift dhe tek
arr = np.array([1,2,2,2,4,6,2,7,8,9])
indx_cift = np.where(arr%2==0)
indx_tek = np.where(arr%2==1)
print(indx_cift, indx_tek)

(array([1, 2, 3, 4, 5, 6, 8], dtype=int64),) (array([0, 7, 9], dtype=int64),)


In [21]:
arr = np.array([34,37,45,44,46,45])
x = [False, False, True, False, True,True]

arr_new = arr[x]
arr_new

array([45, 46, 45])

In [22]:
arr = np.array([34,37,45,44,46,45, 54,67,41,23])
tr_fl = []
for elem in arr:
    if elem>=45:
        tr_fl.append(True)
    else:
        tr_fl.append(False)
tr_fl

[False, False, True, False, True, True, True, True, False, False]

In [23]:
arr45 = arr[tr_fl]
arr45

array([45, 46, 45, 54, 67])

In [24]:
arr = np.array([34,37,45,44,46,45, 54,67,41,23])
np.sort(arr)

array([23, 34, 37, 41, 44, 45, 45, 46, 54, 67])

In [25]:
np.sort(arr)[::-1]

array([67, 54, 46, 45, 45, 44, 41, 37, 34, 23])